import { describe, expect, it } from 'vitest';
import { generateCompatSdl } from '../generate-compat-sdl.js';
import { mergeSchemas } from '../merge-schemas.js';
import { createEnvironmentSchema } from './helpers.js';
import {
  developStarshipSchema,
  productionStarshipSchema,
  stagingStarshipSchema
} from './fixtures/starship-schemas.js';

describe('generateCompatSdl', () => {
  const schemas = [
    createEnvironmentSchema('develop', developStarshipSchema),
    createEnvironmentSchema('staging', stagingStarshipSchema),
    createEnvironmentSchema('production', productionStarshipSchema)
  ];

  it('includes generation metadata in the SDL header', () => {
    const merged = mergeSchemas(schemas, 'develop');
    const sdl = generateCompatSdl(merged);

    expect(sdl.startsWith('# Generated by graphql-schema-env-sync')).toBe(true);
    expect(sdl).toContain('# Base environment: develop');
    expect(sdl).toContain('# Environments: develop, staging, production');
  });

  it('renders object fields with availability comments', () => {
    const merged = mergeSchemas(schemas, 'develop');
    const sdl = generateCompatSdl(merged);

    expect(sdl).toContain('type Starship {');
    expect(sdl).toContain('id: ID!');
    expect(sdl).toContain('Available in: develop');
    expect(sdl).toContain('Missing in: staging, production');
    expect(sdl).toContain('length(unit: LengthUnit = METER): Float');
    expect(sdl).toContain('name: String');
  });

  it('orders scalar and enum definitions before object types', () => {
    const merged = mergeSchemas(schemas, 'develop');
    const sdl = generateCompatSdl(merged);

    const scalarIndex = sdl.indexOf('scalar ID');
    const enumIndex = sdl.indexOf('enum LengthUnit');
    const objectIndex = sdl.indexOf('type Starship');

    expect(scalarIndex).toBeGreaterThan(-1);
    expect(enumIndex).toBeGreaterThan(scalarIndex);
    expect(objectIndex).toBeGreaterThan(enumIndex);
  });
});
