import type {
  CompatArg,
  CompatField,
  CompatSchema,
  CompatType
} from './types.js';

function formatAvailabilityComment(availability: {
  environments: string[];
  missingIn: string[];
}): string {
  const available = availability.environments.join(', ');
  const missing =
    availability.missingIn.length > 0
      ? availability.missingIn.join(', ')
      : 'none';

  return ['Available in: ' + available, 'Missing in: ' + missing].join('\n');
}

function renderFieldComments(field: CompatField): string {
  const lines: string[] = [];

  if (field.description) {
    lines.push(field.description);
  }

  if (field.availability.missingIn.length > 0) {
    lines.push(formatAvailabilityComment(field.availability));
  }

  if (lines.length === 0) {
    return '';
  }

  return `"""\n${lines.join('\n')}\n"""\n`;
}

function renderArg(arg: CompatArg): string {
  const defaultValue = arg.defaultValue != null ? ` = ${arg.defaultValue}` : '';
  return `${arg.name}: ${arg.typeSdl}${defaultValue}`;
}

function renderObjectField(field: CompatField): string {
  const args =
    field.args.length > 0
      ? `(${field.args.map(arg => renderArg(arg)).join(', ')})`
      : '';

  return `${renderFieldComments(field)}  ${field.name}${args}: ${field.typeSdl}`;
}

function renderInputField(field: CompatField): string {
  const defaultValue =
    field.defaultValue != null ? ` = ${field.defaultValue}` : '';
  return `${renderFieldComments(field)}  ${field.name}: ${field.typeSdl}${defaultValue}`;
}

function renderType(type: CompatType): string {
  const description = type.description ? `"""${type.description}"""\n` : '';

  switch (type.kind) {
    case 'SCALAR':
      return `${description}scalar ${type.name}`;

    case 'ENUM': {
      const values = (type.enumValues ?? [])
        .map(value => {
          const comment =
            value.availability.missingIn.length > 0
              ? `  """${formatAvailabilityComment(value.availability)}"""\n`
              : '';
          const valueDescription = value.description
            ? `  """${value.description}"""\n`
            : '';
          return `${comment}${valueDescription}  ${value.name}`;
        })
        .join('\n');

      return `${description}enum ${type.name} {\n${values}\n}`;
    }

    case 'UNION': {
      const members = (type.possibleTypes ?? []).join(' | ');
      return `${description}union ${type.name} = ${members}`;
    }

    case 'INTERFACE': {
      const fields = (type.fields ?? []).map(renderObjectField).join('\n');
      return `${description}interface ${type.name} {\n${fields}\n}`;
    }

    case 'INPUT_OBJECT': {
      const fields = (type.fields ?? []).map(renderInputField).join('\n');
      return `${description}input ${type.name} {\n${fields}\n}`;
    }

    case 'OBJECT': {
      const implementsClause =
        type.interfaces && type.interfaces.length > 0
          ? ` implements ${type.interfaces.join(' & ')}`
          : '';
      const fields = (type.fields ?? []).map(renderObjectField).join('\n');
      return `${description}type ${type.name}${implementsClause} {\n${fields}\n}`;
    }

    default:
      return '';
  }
}

export function generateCompatSdl(schema: CompatSchema): string {
  const header = [
    '# Generated by graphql-schema-env-sync',
    `# Base environment: ${schema.baseEnvironment}`,
    `# Environments: ${schema.environments.join(', ')}`,
    ''
  ].join('\n');

  const kindOrder: Record<CompatType['kind'], number> = {
    SCALAR: 0,
    ENUM: 1,
    INTERFACE: 2,
    UNION: 3,
    INPUT_OBJECT: 4,
    OBJECT: 5
  };

  const body = [...schema.types]
    .sort((a, b) => {
      const kindDiff = kindOrder[a.kind] - kindOrder[b.kind];
      if (kindDiff !== 0) {
        return kindDiff;
      }
      return a.name.localeCompare(b.name);
    })
    .map(renderType)
    .filter(Boolean)
    .join('\n\n');

  return `${header}${body}\n`;
}
